### ISSUE TITLE
plugin-relay cursor based connection example is incomplete

### ISSUE THREAD

**Issue by peacechen** [hayes/pothos#1012]
The example for cursor based connections doesn't work. The connection exposes `before, after, first, and last` args and is missing the `limit, inverted` args. A query attempting to pass those args fails.

https://pothos-graphql.dev/docs/plugins/relay#creating-connections

```
import { resolveCursorConnection, ResolveCursorConnectionArgs } from '@pothos/plugin-relay';

builder.queryField('posts', (t) =>
  t.connection({
    type: Post,
    resolve: (_, args) =>
      resolveCursorConnection(
        {
          args,
          toCursor: (post) => post.createdAt.toISOString(),
        },
        // Manually defining the arg type here is required
        // so that typescript can correctly infer the return value
        ({ before, after, limit, inverted }: ResolveCursorConnectionArgs) =>
          prisma.post.findMany({
            take: limit,
            where: {
              createdAt: {
                lt: before,
                gt: after,
              },
            },
            orderBy: {
              createdAt: inverted ? 'desc' : 'asc',
            },
          }),
      ),
  }),
);
```

I worked around that by manually passing in `args` to `t.connection()`
```
    args: {
      after: t.arg.string(),
      before: t.arg.string(),
      inverted: t.arg.boolean(),
      limit: t.arg.int(),
    },

```

Is there a better way to accomplish this? The default args remain, resulting in a union of `before, after, first, last, limit, inverted`. the `first, last` args don't apply to cursor pagination and it would be better to remove them.

**Comment by hayes** [comment]
This is the expected behavior.  The args you are seeing are the args that a relay connection needs to have.   The `inverted` and `limit` values are calculated based on the args and are designed to simplify the implementation of the connection.

Calling the connection with `first: 20` will result in a limit of 21 to detect if there is a next page. 

Implementing the full cursor pagination in a way that accounts for all the combinations of first last, before, and after is a little complex.  Converting to before, after, inverted and limit makes it much easier to construct the correct database queries

**Comment by peacechen** [comment]
Thanks for explaining the magic behind the scenes
