### ISSUE TITLE
Error TS2351 for new SchemaBuilder when testing with ts-jest

### ISSUE THREAD

**Issue by lpc921** [hayes/pothos#1107]
Code:
```typescript
export const builder = new SchemaBuilder({});
```

Error when running test:
```
error TS2351: This expression is not constructable.
Type 'typeof import("C:/Users/[...]/node_modules/@pothos/core/dts/index")' has no construct signatures.
```

Package versions:
```
"@pothos/core": "3.40.1"
"typescript": "5.2.2"
"jest": "29.7.0",
"ts-jest": "29.1.1",
```

[Repository with error reproduction](https://github.com/lpc921/pothos-jest-issue)

Related: #597

**Comment by hayes** [comment]
I think this is a bug in ts-jest.  If you follow the [esm documentation](https://kulshekhar.github.io/ts-jest/docs/guides/esm-support) it says:
> Ensure that tsconfig has module with value for ESM, e.g. ES2015 or ES2020 etc...

If change your tsconfig to use those settings:

```json
  "module": "ES2022",
  "moduleResolution": "Node",
```
Everything works fine.  The error you are seeing comes from typescript using settings different than those in the tsconfig in the repo (running the build command/tsc works fine).

I'd recommend opening an issue with ts-jest, since this seems related to them changing or not respecting some options in the repos tsconfig.   I personally don't use ts-jest, so not sure about next steps for debugging this further

**Comment by lpc921** [comment]
Thanks so much for your help. It is working for me now.
