### ISSUE TITLE
Relay plugin should allow providing `last` argument by itself

### ISSUE THREAD

**Issue by Emilios1995** [hayes/pothos#1287]
When querying a connection field created with `t.connection`, it's not possible to pass the `last` argument unless `before` is also provided. 

I don't think this validation is correct, as there are valid use cases that call for fetching the last `n` items. Also, there's nothing in the [spec](https://relay.dev/graphql/connections.htm#sec-Pagination-algorithm) implying that it shouldn't be supported. 

Would you be open to a PR that removes it?

**Comment by hayes** [comment]
If that's the case, it's definitely a bug, and I would love a PR to fix it

**Comment by hayes** [comment]
Looking through the code t.connection doesn't do any validation of arguments.

`resolveOffsetConnection` has the limitation you described, because it doesn't know what the offset should be.  I think the `resolveArrayConnection` inherits that limitation, but it should be able to support it because the connection has a fixed/known size.

I'll take a look at fixing that

**Comment by hayes** [comment]
Just pushed a new version that adds a `totalCount` option to `resolveOffsetConnection`, when this is provided, it will allow using `last` without `before`.  Using `resolveArrayConnection` will automatically set totalCount
