### ISSUE TITLE
Exposing externalRef in subgraph even if not exposed in query/mutation

### ISSUE THREAD

**Issue by bloodyowl** [hayes/pothos#1336]
hello!

I'm looking for a way to force the inclusion of a type extension on a given subgraph. I have a schema that doesn't expose any `User` object itself, but I'd still like the type to be shipped in the schema to register the additional fields. 

```ts
export const User = builder.externalRef(
  "User",
  builder.keyDirective(builder.selection<{ id: string }>("id"), false),
  // something like:
  // {exposeOnSubGraphs: ["a", "b"]}
);

User.implement({
  externalFields: t => ({
    id: t.id({ nullable: false }),
  }),
});

builder.objectField(User, "pets", t =>
  // some extensions
);
```

is there a way to make sure that the object is registered in the subgraph?

**Comment by bloodyowl** [comment]
digging a bit more, it seems like a bug in the `hasReturnedInterface` implementation in the subgraph plugin, if an object doesn't implement any interface, it's excluded

**Comment by hayes** [comment]
to clarify, you are using the federation plugin and sub-graph plugin together?

I haven't tested this combination, since they have somewhat opposite goals, but I think the observed makes sense from how these plugins are designed (not saying it can't be fixed, just that everything is "working as expected" based on the original design intention)

The sub-graph plugin prunes all unused types.  This is an important property of the sub-graph plugin. 

The federation plugin makes certain types accessible, that aren't accessible through fields defined in pothos via the `_entities` query.  This query field doesn't get added in Pothos, so the sub-graph plugin doesn't know that these types will become accessible.

`hasReturnedInterface` is working as intended here, it is only responsible for determining if a type implements an interface that is reachable in the subgraph, which would in turn make the type reachable, so it should not be excluded.


I think the correct solution here would be to add a hook to the subgraph plugin options for determining if a type should be included

**Comment by bloodyowl** [comment]
our use case is to be able publish to multiple federated graphs, so I'd say the usage isn't completely opposite, even though I get that it's not usual. 

could it be that the order the plugins interact building the schema that don't give the subgraph build the opportunity to be aware of the entities query?

**Comment by hayes** [comment]
> could it be that the order the plugins interact building the schema that don't give the subgraph build the opportunity to be aware of the entities query?

No, the issue is that the federation plugin adds the _entity query to the build schema directly, which the sub-graph plugin would never see.

I am adding a new option that should help work around this

**Comment by hayes** [comment]
should be released now.  Let me know how this goes!

**Comment by bloodyowl** [comment]
works like a charm! thank you very much!
