### ISSUE TITLE
Scope Auth Plugin introduces Refs undefined error

### ISSUE THREAD

**Issue by YElyousfi** [hayes/pothos#389]
Hello,
 
Attempting to use the scope auth plugin but when it's included I get the following error:
```
Error: Ref undefined has not been implemented
    at ConfigStore.getTypeConfig (c:\...\node_modules\@pothos\core\src\config-store.ts:227:6)
    at BuildCache.getTypeConfig (c:\...\node_modules\@pothos\core\src\build-cache.ts:122:41)
    at map (c:\...\node_modules\@pothos\plugin-scope-auth\src\index.ts:144:29)
    at Array.map (<anonymous>)
    at PothosScopeAuthPlugin.createStepsForType (c:\...\node_modules\@pothos\plugin-scope-auth\src\index.ts:143:33)
    at PothosScopeAuthPlugin.createResolveSteps (c:\...\node_modules\@pothos\plugin-scope-auth\src\index.ts:200:14)
    at PothosScopeAuthPlugin.wrapResolve (c:\...\node_modules\@pothos\plugin-scope-auth\src\index.ts:67:24)
    at reduceRight (c:\...\node_modules\@pothos\core\src\plugins\merge-plugins.ts:71:39)
    at Array.reduceRight (<anonymous>)
    at MergedPlugins.wrapResolve (c:\...\node_modules\@pothos\core\src\plugins\merge-plugins.ts:70:25)
```
I've followed the troubleshooting guide and this error doesn't occur without the plugin. The pothos folder structure in my project is below. The index files in each folder such as `objects` exports each file like this:
```typescript
export * from './Dog'
export * from './Cat'
export * from './external' // this folder has another index that exports PetOwner
```
```
│   builder.ts
│   index.ts // export * from './schema'
│   schematypes.ts
│   schema.ts // imports index
│
├───enums
│       PetType.ts
│       index.ts
│
├───inputs
│       NumberFilterInput.ts
│       index.ts
│
├───interfaces
│       Animal.ts
│       index.ts
│
├───mutations
│       createDog.ts
│       createCat.ts
│       index.ts
│
├───objects
│   │   Dog.ts
│   │   Cat.ts
│   │   index.ts
│   │
│   └───external // External entities via federation
│           index.ts
│           PetOwner.ts
│
├───queries
│       getDogs.ts
│       getCats.ts
│       index.ts
│
├───scalars
│       Date.ts
│       DateTime.ts
│       index.ts
│
├───unions
│       index.ts
│       LoginResult.ts
│
└───_helpers
        extendIdField.ts // helper to extend entities
        index.ts
        ShapeFromInputRef.ts // Gets TS type from InputRef
```
 
The schema.ts file looks like this:
```
import { builder } from './builder'
import './enums'
import './inputs'
import './interfaces'
import './mutations'
import './objects'
import './queries'
import './scalars'
import './unions'
 
export const schema = builder.toSubGraphSchema({})
```
 
The index at the root looks like this:
```
export * from './inputs' // to use inferred types from refs
export * from './schematypes'
export * from './schema'
```
It works when I only import "standalone" portions of the schema like `scalars`, `inputs`, and `enums`. After some playing around with the imports it seems to be interfaces that cause the issue but I can't be sure.

**Comment by hayes** [comment]
Very weird that the plugin changes the behavior.  I do see a potential circular import issue I should fix in pothos. I think what I will do is add a check when defining interfaces that the refs are all defined.  This will let people more easily find when there is an issue, and I should be able to log a message saying exactly how it can be fixed.  The other part of the fix would be to allow interfaces to be defined as `interfaces: () => [Interface1, interface2]` instead, and avoid trying to access the interfaces until the schema is built.  This would likely fix your issue (I am still not sure exactly the issue you are running into is because it should be consistent with and without the plugin). 

I'll probably try to add this some time this weekend.

In the mean time, I can try to help you troubleshoot.  What I would recommend is logging out any interface refs you are using in your schema right before passing them to an object/interface.

eg:
```ts
import { Animal } from '../Interfaces';

console.log(Animal);
builder.objectType('Dog', { interfaces: [Animal] ...});
```

This will hep you track down which interface ref is actually undefined.
Once you know which interface is causing the issue you can try to figure out the circular import pattern that is causing the issue.

One general tip that might help: Try importing directly from the file that defines a type rather than from index files.  This can be slightly more verbose, but importing from index can cause a lot of issues.  In my own projects I have started to avoid using them whenever possible.

Let me know how this goes, and if you make any progress.  Happy to help debug further if the above doesn't get things working.

**Comment by hayes** [comment]
I would probably rewrite my index files to just import rather the to re-export.

```ts
// objects/index.ts
import './Dog'
import './Cat'
import './external' 
```

**Comment by YElyousfi** [comment]
I am referencing all my refs via SchemaTypes where possible. So `interfaces` are just string arrays. I will try the import approach for objects and interfaces.

**Comment by hayes** [comment]
Oh interesting... That is very odd.  I'll have think through how a string could become undefined.  If you are passing in strings everywhere, then I really don't know what's going on.  Not sure if your code is sharable, but if it is I'd be happy to take a look and try to debug it that way

**Comment by hayes** [comment]
I think I figured it out.  It's not an import issue, there is a bug in the scope auth plugin

**Comment by YElyousfi** [comment]
Unfortunately, my code isn't shareable. Happy to discuss further to debug or help create a similar environment.

> I think I figured it out. It's not an import issue, there is a bug in the scope auth plugin

This makes sense as there isn't an issue without the plugin. I did try replacing `export * from` with `import` and that didn't resolve it. What was the bug?

**Comment by hayes** [comment]
This actual issue is pretty complicated, but the simple version is line should pass the interface ref instead of the name here: https://github.com/hayes/pothos/blob/e2ad8c8a7486d8d209f6cd44a01d283104945659/packages/plugin-scope-auth/src/index.ts#L144

The underlying issues is obfuscated by generic types behaving weird in plugin internals since it doesn't know what type names you passed the the builder constructor.

**Comment by hayes** [comment]
Merged a fix for this issue, should be published in a few minutes, let me know if you have any more issues after upgrading.

Also added some of the ref verification logic, and the ability to lazy load interfaces by wrapping them in a function as described above (this probably isn't relevant to your use case).

**Comment by YElyousfi** [comment]
So far, so good! Don't see the issue anymore. 

Thank you for getting this out so quick. I've really enjoyed using pothos.
