### ISSUE TITLE
How to use the types for resolvers?

### ISSUE THREAD

**Issue by shahinghasemi** [hayes/pothos#397]
Hi! this is my `Object`:
```
const UserS = builder.simpleObject('UserS', {
  fields: (t) => ({
    user: t.prismaField({
      type: 'User',
      nullable: true,
      resolve: async (query, parent, args, context, info) => {
        return await prisma.user.findUnique({ where: { id: 32 } });
      },
    }),
    combinedString: t.string(),
    combinedInt: t.int(),
  }),
});
```
`Query`:
```
builder.queryType({
  fields: (t) => ({
    myUser: t.field({
      type: UserS,
      resolve: (parent, args, context, info) => resolver(),
    }),
  }),
});
```
and the resolver function which resolves `myUser` : 
```
import { User } from '@prisma/client';
function resolver(): { user: User; combinedString: string; combinedInt: number } {
  return {
    user: {
      createdAt: new Date(),
      id: 22,
      phone: '092389j',
    },
    combinedInt: 389,
    combinedString: 'stri',
  };
}
```
However as can be seen I have used `{ user: User; combinedString: string; combinedInt: number }` type for my resolver function. 

This is my question: How can get the types from `UserS` directly? I tried something like 
`function resolver(): typeof UserS {...}` but didn't work? is that possible or I should define the types repititively?

**Comment by hayes** [comment]
There are a couple of pieces here to think about.

Generally speaking, I would avoid trying to derive a resolver type from your Types, this is generally a sign you are thinking about your API in the wrong way.  I generally don't explicitly type return types of most functions in my apps unless there is something hard to infer, or I am trying to define a function with a specific type signature.  Pothos will ensure that whatever type your resolver function returns is compatible, so you should say what you are returning rather than what you should return.

Pothos in general is designed to allow a large variety of types and patterns from revolvers, which includes things like iterables and promises. 

In your case, I would just drop the return type from your resolver and it should just work.

Another thing I notice is that you are likely misusing the prisma plugin or the simpleObjects plugin. If you want to use prismaField you should probably use `builder.objectField(UserS, 'user', t => t.prismaField(...))` instead of defining it as part of the simpleObject directly.

`simpleObject` is designed to specifically so that the parent resolvers must return all data to resolver the object without resolvers.   prismaField is specifically for loading data through a prisma call.  If you want to load the user (and nested relations, use prismaField as I described above and don't include the user field directly in the simpleObject call.  Then your resolver won't need to return the user anymore.  Alternatively if you want to load the user ahead of time and return if rom the resolver, the user type should probably not user prismaObject, instead it should be defined as something like `t.objectRef<UserTypeFromPrisma>('User').implement(...)`.  Then you can define the user field with `t.field({ type: User })` without a resolver. 

All that being said, you can get a type from an object ref with something like:

```ts
type ShapeFromRef<T> = T extends PothosSchemaTypes.ObjectRef<infer P> ? P : never;
type UserType = ShapeFromRef<typeof UserS>
```

**Comment by shahinghasemi** [comment]
Thank you for your interesting considerations, these are my thoughts which are prone to error:

>Generally speaking, I would avoid trying to derive a resolver type from your Types, this is generally a sign you are thinking about your API in the wrong way. I generally don't explicitly type return types of most functions in my apps unless there is something hard to infer, or I am trying to define a function with a specific type signature. Pothos will ensure that whatever type your resolver function returns is compatible, so you should say what you are returning rather than what you should return.

I wanted to modulize the code base with separate resolver files. I can’t understand how is that possible without any type declarations for resolvers, however, I CAN put all my resolvers into the schema file without any type declaration but then we are going to have a long unmaintainable TS file with schemas/resolvers which is hard to modify therefore I came to this solution to create separate resolver files from schema files and put my business logic into them. something like this:

```
builder.queryType({
  fields: (t) => ({
    me: t.prismaField({
      type: Y,
      nullable: true,
      resolve: async (query, parent, args, context, info) => meResolver() // ~100 lines of buissnes logic
    }),
    findBasket: t.field({
      type: X,
      resolve: (parent, args, context, info) => findBasketResolver() // ~100 lines of buissnes logic
    }),
    findLocation: t.field({
      type: Z,
      resolve: (parent, args, context, info) => findLocationResolver() // ~100 lines of buissnes logic 
    }),
  }),
});
```
I wonder if I could have a production pothos code base to see how is it handled in a maintainalbe way!.

**Comment by hayes** [comment]
There are a number of things you can do here:

The simplest options i to use the `builder.queryField` and `builder.objectField` methods which allow you to add single fields  to the corresponding type.  this would look something like the following, and can be put into a file by itself.  You just need to define 

```ts
// Define the query type once (I often do this in the same file I create the builder
builder.queryType({});

// resolvers/me.ts
builder.queryField('me', t => t.prismaField({
      type: Y,
      nullable: true,
      resolve: async (query, parent, args, context, info) => meResolver() // ~100 lines of buissnes logic
    }))
```

I put together a few more examples of different ways you can type (or not type) those resolver functions here: https://stackblitz.com/edit/typescript-wvxumc?file=index.ts

**Comment by shahinghasemi** [comment]
Thank you dear @hayes I got my answer. I have got two more questions and would be really happy to hear your insighful answer:

-  Out of curiosity, would you elaborate on this: 
     > ... this is generally a sign you are thinking about your API in the wrong way

     How do you write your API, specifically about the flow you follow to design, implement, and test them. 
- Pothos is categorized as code-first packages as opposed to SDL-first packages. In my previous project, I've been working with the SDL-first approach (first writing the schemas in SDL then generating the types using code-gen and write the resolvers ...), and now I switched to Pothos to try the code-first approach, It feels really smooth to write GQL API, however, I'm not sure how code-first approach solves the SDL main drawback with emerging the tools like code-gen: "syncing the types and resolvers".

**Comment by hayes** [comment]
> Out of curiosity, would you elaborate on this:
Basically what I mean by this is that for very simple greenfield graphql APIs your data and API might be similar shapes.  In more realistic scenarios you generally want some layer of abstraction between the 2.  You generally want a very well thought out API that is more stable.  The data backing your API will often change over time, or be stitched together from a variety of sources. 

One of the core principles I had in mind when designing the Pothos API was that your data should not define you schema, or conversely your API should not dictate the shape of data your backend needs to conform to.   This can be seen in a number of places.  When defining object types you have a number of ways to define the data that represents an object (though a generic in the builder constructor, using classes, using object refs, or by using a plugin that provides type info eg prisma).  The data can really be anything: a string, a class, a type, or even a union, and pothos will ensure that your resolvers enforce something that produces a functional API.   Another example is the t.expose methods.  While its useful to expose data without having to write out a resolver.  Pothos forces you to specify both the type and the field name when exposing a field.  This ensures that if your data sources change you will get type errors, but the generated schema will remain the same unless you update your implementation to change the the field name or type to match your new format of your data source.

This philosophy is also why the simple-objects API is a plugin and not part of the core API.  The core flow in a Pothos based API should be telling pothos the types of your data as it already exists, and describing the API you want to expose, and then having pothos enforce types in resolvers that join those 2 distinct schemas rather than building an API around your data, or forcing you to format your data around your API.

> Pothos is categorized as code-first packages as opposed to SDL-first packages... "syncing the types and resolvers".

The answer to this is somewhat similar to above.  Pothos gives you a wide variaty of ways to link data to your schema without being opnionated about how that data maps to your resolvers.   The goal is that you shouldn't need to make your data match your API, and then resolvers just implement the conversions from the data you have to the data you want to expose.  This simple-objects plugin kind of negates this pattern, but for very simple objects (hence the name) just returning the data in the same format as the API exposes can be nice)

One of the things code-first enables is that it you get to define everything in one API.  The pothos plugin system lets you use the same type system for defining the schema, resolvers, auth, and many other schema wide concerns without having to replicate the same thing in a bunch of different places.

**Comment by hayes** [comment]
Going to close this, but let me know if you still have questions.
