### ISSUE TITLE
Validation plugin error "Intersection results could not be merged" when using zod string schema with `trim`

### ISSUE THREAD

**Issue by pajecawav** [hayes/pothos#412]
I have a `zod` string schema `z.string().trim()` and when I'm trying to use it with Pothos validation plugin I get an error "Intersection results could not be merged".

Server code:

```ts
import { createServer } from "@graphql-yoga/node";
import SchemaBuilder from "@pothos/core";
import ValidationPlugin from "@pothos/plugin-validation";
import { z } from "zod";

const schema = z.string().trim();

const builder = new SchemaBuilder({ plugins: [ValidationPlugin] });

builder.queryType({
  fields: (t) => ({
    hello: t.string({
      args: {
        name: t.arg.string({
          validate: { schema },
        }),
      },
      resolve: (parent, { name }) => `hello, ${name || "World"}`,
    }),
  }),
});

const server = createServer({
  schema: builder.toSchema({}),
  maskedErrors: false,
});

server.start();
```

Query:

```graphql
query {
  hello(name:"\n\n")
}
```

Error:

```json
{
  "errors": [
    {
      "message": "[\n  {\n    \"code\": \"invalid_intersection_types\",\n    \"path\": [\n      \"name\"\n    ],\n    \"message\": \"Intersection results could not be merged\"\n  }\n]",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "hello"
      ]
    }
  ],
  "data": null
}
```

Package versions:

```
@graphql-yoga/node 2.9.0
@pothos/core 3.11.0
@pothos/plugin-validation 3.4.1
graphql 16.5.0
zod 3.17.3
```

I'm not sure if the problem is in validation plugin, but following code works as expected:

```ts
const schema = z.string().trim();
console.log(schema.safeParse("\n\n"));
console.log(await schema.safeParseAsync("\n\n"));
console.log(schema.safeParse("\n\nfoo\n\n"));
console.log(await schema.safeParseAsync("\n\nfoo\n\n"));
// { success: true, data: '' }
// { success: true, data: '' }
// { success: true, data: 'foo' }
// { success: true, data: 'foo' }
```

**Comment by hayes** [comment]
Thanks for reporting this.  This looks like an issue with some new zod functionality that didn't exist when I first designed this plugin.  Unfortunately I don't see a quick fix for this, and it might take some large internal refactoring to work around it.

Basically it comes down to something like this:

When you have validation for a field it needs to combine validators from a few different places.  It currently does this using schema1.and(schema2).  The plugin is written in a way where it doesn't know that the schema option is the only thing that is provided so it ends creating a schema like  `zod.unknown().and(zod.string().trim())`  When zod runs the `and` part, I think it compares the resulting data from each operation, and notices that the strings no-longer match after running the and, and raises the error you are seeing.

I don't have an ETA on when I can figure out a good solution to this issue, but if you have any suggestions, I'm open to ideas.   The logic that builds the schemas is fairly complex, there are some things I could do like check if the left hand schema is `unknown` or `any` and then ignore it instead of doing an intersection, but that only works for the most simple cases.   Schemas that modify data just don't make a lot of sense with the way the API is currently designed.  I have been thinking about re-designing the validation API (or creating a simpler alternative) for a while, so this may require that high level redesign to land to fix this issue.

The current workaround would be do just move the validation inside the resolver, which is unfortunate, but should still work.

**Comment by remonke** [comment]
> Thanks for reporting this. This looks like an issue with some new zod functionality that didn't exist when I first designed this plugin. Unfortunately I don't see a quick fix for this, and it might take some large internal refactoring to work around it.
> 
> Basically it comes down to something like this:
> 
> When you have validation for a field it needs to combine validators from a few different places. It currently does this using schema1.and(schema2). The plugin is written in a way where it doesn't know that the schema option is the only thing that is provided so it ends creating a schema like `zod.unknown().and(zod.string().trim())` When zod runs the `and` part, I think it compares the resulting data from each operation, and notices that the strings no-longer match after running the and, and raises the error you are seeing.
> 
> I don't have an ETA on when I can figure out a good solution to this issue, but if you have any suggestions, I'm open to ideas. The logic that builds the schemas is fairly complex, there are some things I could do like check if the left hand schema is `unknown` or `any` and then ignore it instead of doing an intersection, but that only works for the most simple cases. Schemas that modify data just don't make a lot of sense with the way the API is currently designed. I have been thinking about re-designing the validation API (or creating a simpler alternative) for a while, so this may require that high level redesign to land to fix this issue.
> 
> The current workaround would be do just move the validation inside the resolver, which is unfortunate, but should still work.

Hey, what about zod `.pipe()` method? It does work just fine in this scenario, as it simply passes down the value without checking if it matches with the first validator.

**Comment by hayes** [comment]
@remonke thanks for the suggestion! publishing a new version with that now, seems to work well

**Comment by hayes** [comment]
new version of the plugin is published with this suggestion!

**Comment by remonke** [comment]
yay thanks bro ☺️
