### ISSUE TITLE
globalID arguments should allow you to define the expected type

### ISSUE THREAD

**Issue by hayes** [hayes/pothos#415]
`t.arg.globalID({ type: SomeType })` should be allowed, and then validate that incoming ids match the expected type.

**Comment by tslater** [comment]
I'm having trouble trying to understand how to use globalId. Is it currently hard-coded to only work with `typename:integer`? Is it possible to use strings of buffers? How would I customize?

**Comment by hayes** [comment]
This issue is related to something else, it's about expecting IDs for specific graphql types.   Global IDs are always going to be strings for the ID portion.  You can encode/decode that string however you want afterwards.  Do you have aore concrete example of what you are trying to do?

**Comment by tslater** [comment]
So my database type for ids is Binary(16) (Buffer in Node/Prisma client). I'm trying to use . When using vanilla JS GraphQL, I use an ID Scalar to handle converting the globalId to { type: string, id: Buffer }, without typesafety. Using Pothos, I'd love to be able to figure out how to do the same thing.

I was having trouble understanding the docs (if I figure it out, I'd love to contribute to improve them if that is helpful!).

So I was trying something here, but the id, like you said is a string. I noticed in [plugin-relay/src/field-builder.ts](https://github.com/hayes/pothos/blob/013fb30286e51108997f3973379fd6530e3035e6/packages/plugin-relay/src/field-builder.ts#L99) in the source code it is converted to via `String()` to a string type. I experimented with trying to get my buffer back from the string with `Buffer.from(id, `utf8`)`, (utf8 is the default for `String()`). I wrestled with that until I realized that the string/Buffer converstion, even with the same encoding is [asymmetrical if it isn't a valid string](https://stackoverflow.com/questions/70162412/nodejs-asymmetrical-buffer-string-conversion) (which happens with arbitrary binary values)!!

So I tried editing 'plugin-relay/src/field-builder.ts' to remove the `String()`, but I realized it had already been converted in the resolver, so I used `parent.id` and that worked...but obviously it is a hack and I yet to understand all the code here.

By the way, quick pause to pay you a huge compliment. This Pothos is totally the way to go. I've fought other packages much much harder for basic things. Clearly this is the best designed GraphQL + TypeScript package in the universe!! I have a sense of complex this whole thing is to solve!!!!


Anyway...with all of my patchy bad edits, this is what I got working, and what I'd like to see in the interface. Or perhaps another symmetry safe Buffer/string conversation would also cover us...ideally keep it short for URLs...the `utf8` string is long...

```
    encodeGlobalID: (
      typename,
      id,
    ) => {
      if (Buffer.isBuffer(id)) {
        const idValues = [typename, id.toString(`hex`)]
        return Buffer
          .from(
            idValues.join(':'),
            'utf8'
          ).toString('base64')
      }
      throw Error(`Unexpected type!`)
    },
    // @ts-ignore
    decodeGlobalID: (textId: string) => {
      const [typename, idString] = Buffer.from(textId, 'base64').toString('utf8').split(':')
      return { typename, id: Buffer.from(idString, 'hex') }
    },
    ```


I'd also love to figure out how to type inputs, arguments, and fields so that Prisma connections, relay plugin etc. etc. to give me back a buffer on `id.id`... i.e. all have the correct type information.

Hopefully I'm explaining this well. I would be much obliged for any insight!

**Comment by hayes** [comment]
I think if you have buffer based fields you want to use as ids you could do something like this: https://codesandbox.io/s/practical-euclid-ufutsg?file=/index.ts.  

If you have ideas on how to make this work more generally I'm open to suggestions, but not sure where we would get the type information on what the type behind and ID actually is.  String is the only type that makes sense as a global id type, since fundamentally ids are always encoded as strings.  Anything else is just decoding a string into an ID.  I think the easiest option is to just have a decodeID/encodeID function you call when returning an ID, or when receiving an id as an argument.

**Comment by tslater** [comment]
Yeah, if I'm understanding you correctly, and encodeID/decodeID (essentially changing how you call toString) would solve my main blocking issue!

**Comment by tgriesser** [comment]
Was about to log this as a feature idea, would love to see the ability to narrow which "typenames" are accepted as a globalId, rather than needing to include that in each resolver. API idea:

```ts
t.arg.globalIdFor({ type: User }) // Can take User.id as input
```

```ts
t.arg.globalIdFor({ type: [User, Post] }) // can take either a User.id or Post.id as input
```

Somewhat related, and I think along the lines of what @tslater is getting at, it'd be great if we could define what the type is for the decoded `id`, assuming we know the possible accepted "types", reducing the need to cast all over the place.

> If you have ideas on how to make this work more generally I'm open to suggestions, but not sure where we would get the type information on what the type behind and ID actually is.

What do you think about adding an option to the `id` when creating the node:

```ts
const TodoListIten = builder.node('TodoListItem', {
  id: {
    resolve: (o) => o.id,
    transform: (id) => Number(id)   // string -> number
  },
  fields: (t) => ({
    // ...
  }),
})
```

where the `transform` added there takes the string result of the `decoded.split(':')[1]` (API naming idea from [zod](https://github.com/colinhacks/zod#transform), was also considering `cast`).

**Comment by hayes** [comment]
I like the idea @tgriesser.  Propagating the information about the ID type would require a bit of work but should be possible.  

I think `builder.node` would need to be updated to return a sub-class of ObjectRef that can store the type information for how an ID will be parsed, allowing `t.arg.globalIDFor` to infer the correct type from the ref.

I'm not sure if `globalIdFor` needs to be a new method, I think we could probably get away with just making `type` optional, or maybe `t.arg.globalID({ for: User })`. 

regarding `transform`, I am leaning towards `parse` as name for the field (aligns with how other scalars are parsed), but don't have a strong preference.

**Comment by tgriesser** [comment]
> I'm not sure if globalIdFor needs to be a new method, I think we could probably get away with just making type optional, or maybe t.arg.globalID({ for: User }).

Yeah, if we can avoid a new method, that'd be great - wasn't sure if it'd be easier to type if it were required, but I'm sure it's  nothing some clever type mapping couldn't figure out.

> regarding transform, I am leaning towards parse as name for the field (aligns with how other scalars are parsed), but don't have a strong preference.

Don't have a strong preference either, `parse` sounds good to me. I was thinking about that initially but wasn't sure if there'd be any confusion with that term since it's not a scalar, but on second thought I guess it is actually a scalar and it maps similar to what `parseValue` is doing. 

Any feedback on whether it'd be ok to allow a list of types: `{ for: Type | Type[] }`

**Comment by hayes** [comment]
> Any feedback on whether it'd be ok to allow a list of types: { for: Type | Type[] }

I don't see why not, if there is a use case for it, I don't really see a downside

**Comment by hayes** [comment]
Quickly hacked together a draft of what this could look like: https://github.com/hayes/pothos/pull/781

**Comment by tgriesser** [comment]
Nice! Just commented.

> I don't see why not, if there is a use case for it, I don't really see a downside

Yeah it'd be useful in situations where the field is returning a union or interface and so the ID in the input might be for a number of potentially different types.

**Comment by hayes** [comment]
this is released now
