### ISSUE TITLE
Unable to use custom scalar JSON fields 

### ISSUE THREAD

**Issue by Janushan** [hayes/pothos#465]
I am trying to use Pothos with Prisma and Apollo Server to replace usage of Nexus.

My builder looks like this:
```
import GraphQLJSON from "graphql-type-json";

export const builder = new SchemaBuilder<{
	Context: Context;
  PrismaTypes: PrismaTypes;
	Scalars: {
    Date: {
      Input: Date;
      Output: Date;
    };
		JSON: {
			Input: Prisma.JsonValue;
			Output: Prisma.JsonValue;
		}
  };
}>({
	plugins: [ PrismaPlugin ],
	prisma: {
		client: (ctx) => (ctx.prisma),
		dmmf: (prisma as unknown as { _baseDmmf: Prisma.DMMF.Document })._baseDmmf
	}
});

builder.scalarType("Date", {
	serialize: (date: any) => date.toISOString(),
	parseValue: (date: any) => new Date(date)
});
builder.addScalarType("JSON", GraphQLJSON, {});

```

Mutation looks like this
```
builder.mutationField("createUser", (t) =>
	t.prismaField({
		type: "User",
		nullable: false,
		args: {
			details: t.arg({ type: "JSON", required: true })
		},
```

But when I use it in a mutation argument and run it in Playground I get the below error:
```
TypeError: Cannot read properties of undefined (reading 'name')
    at isValidEnumValue (~/node_modules/@prisma/client/runtime/index.js:42821:61)
    at getGraphQLType (~/node_modules/@prisma/client/runtime/index.js:42770:7)
    at hasCorrectScalarType (~/node_modules/@prisma/client/runtime/index.js:48666:23)
    at scalarToArg (~/node_modules/@prisma/client/runtime/index.js:48962:7)
    at tryInferArgs (~/node_modules/@prisma/client/runtime/index.js:48890:14)
    at valueToArg (~/node_modules/@prisma/client/runtime/index.js:48752:16)
    at ~/node_modules/@prisma/client/runtime/index.js:49000:18
    at Array.reduce (<anonymous>)
    at objectToArgs (~/node_modules/@prisma/client/runtime/index.js:48980:28)
    at tryInferArgs (~/node_modules/@prisma/client/runtime/index.js:48882:40) {
  clientVersion: '4.0.0'
}
```

Is there something I'm doing wrong here?
I have a feeling it's related to the JSON scalar not being recognised

**Comment by hayes** [comment]
Hey, this error looks like it's coming from the prisma client.  It's hard to tell from the context provided, but it looks like the issue is that something being passed a prisma query is not valid.

I don't think this error is directly related to using a JSON scalar in pothos.

I don't see enough information to know what's going on here, but based in the question, one possibility is that you are using a JSON scalar field to pass a values directly into the prisma client from a json argument.  If this is the case, I would recommend trying to log out the value before passing it to prisma, to see if the value is what you expect.  If this is not the case, maybe providing a more complete example of what you are doing (and when the error is occurring  (start up, when running a specific query, etc) might be helpful.

**Comment by Janushan** [comment]
It seems like it wasn't getting recognised as a JSON object until parsing and stringifying

**Comment by hayes** [comment]
glad you figured it out!
