### ISSUE TITLE
Fields missing in type

### ISSUE THREAD

**Issue by felixhaeberle** [hayes/pothos#507]
Hi,

first of all thank you for providing such a great tool! We really like it!
We found one strange behavior or maybe we don't understand the API the right way:

TypeScript can't find the fields `createdAt` and `modifiedAt` from Prisma.

<img width="605" alt="Bildschirmfoto 2022-08-08 um 20 52 56" src="https://user-images.githubusercontent.com/34959078/183493549-5dfba992-ad0b-40fa-a4f5-922deebede0b.png">

The error is: 
`Argument of type ""createdAt"" cannot be assigned to parameter of type "CompatibleTypes<ExtendDefaultTypes<{ PrismaTypes: PrismaTypes; Context: GraphQLContext; DefaultFieldNullability: true; }>, Idea, "String", boolean>".ts( 2345)`

<img width="562" alt="Bildschirmfoto 2022-08-08 um 20 52 11" src="https://user-images.githubusercontent.com/34959078/183493394-859fffbe-bac4-48b1-9d01-a39f1b26007b.png">

<img width="413" alt="Bildschirmfoto 2022-08-08 um 20 52 27" src="https://user-images.githubusercontent.com/34959078/183493555-3dfd5d62-8a8a-4b6a-9c3f-3ba5a25938c4.png">

But the data of the values is arriving in the frontend, so the code works. 
What are we doing wrong here?

Thank you very much for your help!!

**Comment by hayes** [comment]
`t.expose*` has one of the worst error messages in the pothos API, I've tried to find ways to improve it, but so far I haven't found a way to get a good error message without degrading something else. 


The issue here is that createdAt and modifiedAt are not "compatible" with a string field.  Obviously they are working, but they are not compatible for a typescript perspective.  String fields by default only allow you to return properties/fields that are actually strings.

There are a bunch of ways you can work around this.  The most correct would probably be something like:  `t.string({ resolve: idea => idea.createdAt.toString()` or to create a `DateTime` scalar:  `t.expose('createdAt', { type: DateTime })`.  You can also use a type case `t.exposeString('createdAt' as never)` (this is more of a hack), or you can even update pothos to allow Date objects in string fields:  `const builder = new SchemaBuilder<{ Scalars: { String { Input: string; Output: string | Date } } }>({...})`  This will let you return a Date object for any string field.  This probably isn't a good idea, but just here to show where the restrictions for what is allowed in a `string` field comes from.

**Comment by felixhaeberle** [comment]
The first suggesstion worked 🥳
Thank you a ton, also for the explanantion!!! 🎉🎉 
Have a nice day, you rock! 🏄
