### ISSUE TITLE
Inferring prismaField's parent breaks simpleObject definitions

### ISSUE THREAD

**Issue by Gomah** [hayes/pothos#512]
Hey @hayes 👋🏻 ,

Thank you so much for this library, we've been using it in production for the past 2 months and we love it so far!

We recently encountered an issue when upgrading `@pothos/plugin-prisma` from 3.18.0:

We are using the simple object plugin to define a [GraphQL Type that includes two prisma fields](https://github.com/Gomah/pothos-prisma-simple-object-issue/blob/main/src/schema.ts#L37), when upgrading to any new version (3.20.0 or 3.21.0), the [`PrismaFieldOptions` type breaks the `resolve` type in the field definition](https://github.com/Gomah/pothos-prisma-simple-object-issue/blob/main/src/schema.ts#L47).

Reproduction repo: https://github.com/Gomah/pothos-prisma-simple-object-issue

**Comment by hayes** [comment]
Hey, thanks for reporting!  Just pushed a fix.  Should be published in a few minutes

**Comment by hayes** [comment]
Related:  I am fixing this compatibility issue because I think it's technically wrong, but you probably shouldn't use prismaField inside a simple object like that.    simpleObjects are designed to infer the expected parent type (the type you need to return from a parent resolver) from the fields defined for the type.  When you define a prismaField inside a simple object, you will be expected to pre-load that field from the parent resolver, and then the resolver will load the same thing again.

Instead what you can do is use builder.objectField.  Eg:

```ts
cont Foo = builder.simpleObject('Foo', { fields: t => ({ ... }) })

builder.objectField(Foo, 'post', t => t.prismaField({ type: 'Post', resolve: () => ... }))
```

**Comment by hayes** [comment]
fix should be published now

**Comment by Gomah** [comment]
> you probably shouldn't use prismaField inside a simple object like that

Thank you for explaining and adding a solution, it works well!
