### ISSUE TITLE
Validation Plugin with custom message is not working

### ISSUE THREAD

**Issue by vimutti77** [hayes/pothos#515]
It always return `Unexpected error.`

Sample code
```
builder.queryType({
  fields: (t) => ({
    withMessage: t.boolean({
      nullable: true,
      args: {
        email: t.arg.string({
          validate: {
            email: [true, { message: "invalid email address" }],
          },
        }),
      },
      resolve: () => true,
    }),
  }),
});
```

Query
```
query {
  withMessage(email: "not email")
}
```

Expect Result
```json
{
  "errors": [
    {
      "message": "invalid email address",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "withMessage"
      ]
    }
  ],
  "data": {
    "withMessage": null
  }
}
```

Actual Result
```json
{
  "errors": [
    {
      "message": "Unexpected error.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "withMessage"
      ]
    }
  ],
  "data": {
    "withMessage": null
  }
}
```

**Comment by hayes** [comment]
Are you using something like graphql yoga that has error masking enabled by default? https://www.graphql-yoga.com/docs/features/error-masking

**Comment by vimutti77** [comment]
Oh, it's an error masking from graphql Yoga as you said.

Actually, I have a plan to migrate from nexus to pothos, so I did some research using the examples provided by the repos that come with graphql yoga.

But now, when I disabled the error masking by using
```ts
createServer({
  maskedErrors: false,
})
``` 

And after I run the query, I get
```json
{
  "errors": [
    {
      "message": "[\n  {\n    \"validation\": \"email\",\n    \"code\": \"invalid_string\",\n    \"message\": \"invalid email address\",\n    \"path\": [\n      \"email\"\n    ]\n  }\n]",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "withMessage"
      ]
    }
  ],
  "data": {
    "withMessage": null
  }
}
```

I'm not really sure that this is the correct behavior. May be it should be something like
```json
{
  "errors": [
    {
      "message": "invalid email address",
      "code": "invalid_string",
      "validation": "email",
      "locations": [...],
      "path": [
        "withMessage",
        "email"
      ]
    }
  ],
  "data": {
    "withMessage": null
  }
}
```

**Comment by hayes** [comment]
The way this currently works is that when validation fails, zod throws an error.  Pothos doesn't currently intercept or processes this error in any way.  I wanted to avoid having any error formatting logic in Pothos because the shape of details of Zod errors has changed significantly over time, and there are users using a wide range of versions, meaning its hard to have one way to normalize all validation errors.

What I have done in the past is use error formatting features of the server I was using (apollo and graphql helix both have very simple apis for this, I am not sure about yoga).  This lets you do formatting of zod errors at the application level, and gives you more control.

I know the above isn't a great answer for your use case.  I think there are probably 2 things we need to add:

1. Documentation on how to format errors with a number of common server setups
2. Add a new callback/option to the plugin that receives any validation errors and lets you replace the error with a custom error so things can be contained in Pothos and are not dependent on servers supporting error formatting

**Comment by hayes** [comment]
Just pushed a new version that has an option for customizing errors, hope that works for you

**Comment by hayes** [comment]
let me know if you have any issues with this after upgrading
