### ISSUE TITLE
Prisma connection omits edge for take: undefined when there are 21 records

### ISSUE THREAD

**Issue by P4sca1** [hayes/pothos#530]
I noticed that a prisma connection returns 20 records in production, but there are 21 records in the database.

```ts
// ...
// Use prismaConnection instead of relatedConnection because totalCount does not work with filters yet.
// https://github.com/prisma/prisma-engines/pull/3057
gameServers: t.prismaConnection(
	{
		type: 'GameServer',
		cursor: 'id',
		description:
			'Contains all the game servers that are deployed to this machine.',
		complexity: (args) => ({
			field: 10,
			multiplier: args.first ?? args.last ?? 20,
		}),
		shield: or(
			isMachineOfAuthenticatedDaemon,
			belongsToAuthenticatedUser,
			authenticatedUserIsAdmin
		),
		args: {
			where: t.arg({
				type: MachineGameServersFilter,
				defaultValue: { reservation: false },
			}),
			orderBy: t.arg({
				type: GameServerOrder,
				defaultValue: {
					field: GameServerOrderField.CREATED_AT,
					direction: OrderDirection.ASC,
				},
			}),
		},
		resolve: (query, machine, args, { auth }) => prisma.gameServer.findMany({
				...query,
				// Return all nodes for the daemon when first and last argument are missing.
				take:
					auth.daemonIsAuthenticated && !args.first && !args.last
						? undefined
						: query.take,
				where: {
					machineId: machine.id,
					reservation: args.where?.reservation ?? undefined,
				},
				orderBy: convertOrderBy(args.orderBy),
			}),
		totalCount: (machine, args) =>
			prisma.gameServer.count({
				where: {
					machineId: machine.id,
					reservation: args.where?.reservation ?? undefined,
				},
			}),
	},
	{ shield: allow },
	{ shield: allow }
),
// ...
```

When `auth.daemonIsAuthenticated` is true, it is possible to leave out `first` and `last` arguments to fetch all results with a single call. Therefore `take` is set to undefined.
This works as expected, except for one edge case:

**When there are 21 (DEFAULT_SIZE+1) records returned from prisma, only 20 are returned in the GraphQL response.** When there are 22 or more, all of them are returned correctly.
I found the following code, which is likely causing the issue, but I don't understand the use case for `gotFullResults`. https://github.com/hayes/pothos/blob/9168d902491c6e66f838ed22dd57b51bb2788a47/packages/plugin-prisma/src/util/cursors.ts#L260-L265

**Comment by hayes** [comment]
I think the bug here is that it is not truncating in all cases.  The correct solution would be to set the default size to something higher.  Unfortunately there isn't a way to do this based on the user context.  This is something that should be supported.  I can add support for that.

The way the connection helpers generally work is that based on various inputs (default, max, first, last) the helper knows it should ask for n nodes, but it also needs to know if there is a next page, so it will always request n+ 1, if it receives less than n + 1, it knows there isn't a next page.  For this to work, we need to know how many items are expected.   Deleting the take option from the query breaks the assumption about the returned list attempting to return the number of items requested.

**Comment by hayes** [comment]
Pushed a new version with a new feature that should help:

you should be able to do something like:

```ts
maxSize: (args, { auth }) => auth.daemonIsAuthenticated ? Number.MAX_SAFE_INTEGER : 100,
defaultSize: (args, { auth }) => auth.daemonIsAuthenticated ? Number.MAX_SAFE_INTEGER : 20,
```

and then you don't need to mess with `take` in the resolver.  I would probably use different max/deafult size, depending on your needs.

Let me know if that doesn't solve your issue

**Comment by P4sca1** [comment]
This is a great solution, thank you 🙏
