### ISSUE TITLE
[Prisma Plugin] defaultSize is not used for "last" arg. Incorrect exception thrown.

### ISSUE THREAD

**Issue by BengtHagemeister** [hayes/pothos#532]
When using the prisma / relay plugin, pagination is behaving differently from the documentation. 

`defaultSize: (default: 20) The default page size to use if first and last are not provided.`

When last is not provided the following exception is thrown: 

https://github.com/hayes/pothos/blob/8ca9b66cf7c9bb63c5d100757ffad65c17861f9d/packages/plugin-prisma/src/util/cursors.ts#L229-L231

I think the exception can be safely deleted since the defaultSize is used when `last` is not provided:

https://github.com/hayes/pothos/blob/8ca9b66cf7c9bb63c5d100757ffad65c17861f9d/packages/plugin-prisma/src/util/cursors.ts#L243

Let me know if I should make a pull request. Maybe there should also be a test added with a missing `last` argument (this is already the case with first).

**Comment by hayes** [comment]
This sounds right, feel free to open a PR, or I can fix it when I'm back at a computer.   I would double check that this doesn't open up a way to request more than the max number of rows (I think there are checks that should prevent this, but things like 'before x, first n' are allowed by the relay spec, but shouldn't be allowed here

**Comment by hayes** [comment]
I think the bug here is that it is not truncating in all cases.  The correct solution would be to set the default size to something higher.  Unfortunately there isn't a way to do this based on the user context.  This is something that should be supported.  I can add support for that.

The way the connection helpers generally work is that based on various inputs (default, max, first, last) the helper knows it should ask for n nodes, but it also needs to know if there is a next page, so it will always request n+ 1, if it receives less than n + 1, it knows there isn't a next page.  For this to work, we need to know how many items are expected.   Deleting the take option from the query breaks the assumption about the returned list attempting to return the number of items requested.

**Comment by hayes** [comment]
Published a new version that should fix this
