### ISSUE TITLE
[Prisma plugin] Example for using mutations

### ISSUE THREAD

**Issue by cimchd** [hayes/pothos#624]
I just started using Pothos. An dit looks really good. Thanks for the great work. :-)

But I am missing an example of how to use mutations with the Prisma plugin. I found only examples on how to use queries.

**Comment by hayes** [comment]
There aren't a lot of examples of this right now.  It's currently a more manual process than defining queries, but you can see an example here: https://github.com/hayes/pothos/blob/main/examples/complex-app/src/schema/team.ts

If there are specific things you are having trouble with let me know, but the general solution requires defining input types  using the normal input type builder methods, and then using those input types with a `t.prismaField`.  There currently are no helpers for generating input types that match the types in your schema, so that part is currently requires just manually building those types.  It's something I have been thinking about, but gets very complicated when you start looking at all the different ways you can model relations.

**Comment by cimchd** [comment]
Thanks :-)

In case someone else is also searching for a mutation example with prisma, this is what I did:

```prisma
// prisma.schema
model Customer {
  id    String     @id @default(cuid())
  name  String
}
```

```ts
// schema.ts
import { builder } from './builder.js';
import { db } from './context.js';

const CreateOneCustomerInput = builder.inputType('CreateOneCustomerInput', {
  fields: (t) => ({
    name: t.field({ type: 'String', required: true }),
  }),
});

const CustomerUniqueInput = builder.inputType('CustomerUniqueInput', {
  fields: (t) => ({
    id: t.field({ type: 'String', required: true }),
  }),
});

builder.mutationType({
  fields: (t) => ({
    createOneCustomer: t.prismaField({
      type: 'Customer',
      args: {
        input: t.arg({ type: CreateOneCustomerInput, required: true }),
      },
      resolve: (query, _, { input }) =>
        db.customer.create({
          ...query,
          data: {
            name: input.name,
          },
        }),
    }),
    updateOneCustomer: t.prismaField({
      type: 'Customer',
      args: {
        input: t.arg({ type: CreateOneCustomerInput, required: true }),
        where: t.arg({ type: CustomerUniqueInput, required: true }),
      },
      resolve: (query, _, { input, where }) =>
        db.customer.update({
          ...query,
          data: {
            name: input.name,
          },
          where,
        }),
      )
    }),
  })
})
```
