### ISSUE TITLE
Scope Auth throw/return custom error within scope

### ISSUE THREAD

**Issue by haleksandre** [hayes/pothos#628]
I have an auth scope that does a few checks & throws an appropriate custom error message whenever it fails. An example flow is on queries/mutations the scope checks if the user is in the context first, and it throws an `UnauthorizedError` error but if the user is present & doesn't have allowed access it throws a `ForbiddenError` error. This scope is used throughout the app on multiple query & mutation fields. Right now it seems that the only way to throw the custom errors is to implicitly have a `unauthorizedError` function & use the `result` param & throw the `result.failure` manually from there. It would be preferable if I could either throw the error directly within the scope (this is what I was doing which works when you have a single scope but doesn't work with multiple with `$any`) but another option could be to return an `Error` object & the scope could catch the error & deal with throwing that error automatically.

I think this would add flexibility to the plugin & it would remove some needed boilerplate code to achieve this result.

Would it be something you would be willing to add to your scope-auth plugin?

**Comment by hayes** [comment]
Here is a rough idea of how this could work: https://github.com/hayes/pothos/pull/629. Does this look like it would solve your use case?  I need to write a bunch of tests and make sure the actually works (haven't actually run any of this code yet, just quickly pushed up a rough set of changes as way to illustrate the potential solution)

**Comment by haleksandre** [comment]
That was quick! If I understand the code correctly all I'd  need to do is set an option `treatErrorsAsUnauthorized: true` within the ` scopeAuthOptions`. This would make Auth Scope catch the thrown error within the scope, cache it & then return the error so that the graphql server can handle it correclty? If so then this is perfect.

**Comment by hayes** [comment]
> That was quick! If I understand the code correctly all I'd need to do is set an option `treatErrorsAsUnauthorized: true` within the ` scopeAuthOptions`. This would make Auth Scope catch the thrown error within the scope, cache it & then return the error so that the graphql server can handle it correclty? If so then this is perfect.

That is generally how it would work, but gets slightly more complicated in certain situations.  For functions defined inline on a field or a type, the above description is accurate.  If you define scopes as functions, and one of those functions throws, it works slightly different.  The get to that point, you would either have defined scope map on a field or type, or returned a scope map from a function on a field/type.  This might look something like: `authScopes:(post) => ({ loggedIn: true, publicPost: post.id  })`  which should allow the user to read the field if they are logged in, or the post is public.  In this case, if the user is not logged in, and the publicPost scope throws, you have 2 things that failed.  This would fall back to the generic auth error rather than re-throwing the error thrown by `publicPost`.  Without this change (or with the new setting set to false) this would previously just thrown the `publicPost` error.  

This may not exactly cover your use case, depending on what you expect when an `$any` or just a field with multiple scopes fails.  With this change, you could probably still customize this with a custom `unauthorizedError` method.

**Comment by haleksandre** [comment]
I'd prefer one of the scope errors to be 're-thrown' (or an array of both, if possible? not sure how GraphQL handles multiple errors when they populate the errors array within the response or if it's doable outside GraphQL). But if you think it would be better to throw the generic error, with info of one or both failed scope errors accessible within `unauthorizedError`, then this would be fine as well.

**Comment by hayes** [comment]
Merged the new feature.

See this new section in the docs: https://pothos-graphql.dev/docs/plugins/scope-auth#surfacing-errors-thrown-in-authorization-checks

`treatErrorsAsUnauthorized` Will cause thrown errors to be treated as auth failures (that apropriately get caught, and work in `$any` and will trigger the `unauthorizedError` callback.  Errors thrown on specific field or type will be re-thrown by default, but if the error is thrown inside a scope function defined in the builder setup, you will need to implement a custom `unauthorizedError` callback as described in the link above to re-throw those errors.  The reason for that is that those errors will always be wrapped inside an implicit `$any` (when define an object with a map of scopes, even if its just one, that is treated as an $any).   Throwing the first error when all scopes in an $any fail isn't a good default, but is easy to do yourself.

Let me know if this works for you
