### ISSUE TITLE
Cannot find module '@pothos/plugin-prisma/generated' or its corresponding type declarations.

### ISSUE THREAD

**Issue by yovanoc** [hayes/pothos#661]
I think it's because the exports field in the package.json doesn't tell that we can import this generated.ts file. I'm using esm in a turbo Monorepo.

**Comment by JipSterk** [comment]
Hi i don't have a turbo monorepo but do use pnpm workspaces and think i ran in to the same issues as you.
The command `primsa generate` would overwrite for each prisma schema and output to the same location in the `node_modules` luckily you can configure the output of prisma and or pothos.
```.prisma
generator client {
    provider      = "prisma-client-js"
    binaryTargets = ["native", "debian-openssl-1.1.x"]
    output        = "../node_modules/.prisma/client"
}

generator pothos {
    provider     = "prisma-pothos-types"
    clientOutput = ".prisma/client"
    output       = "../src/__generated__/pothos.ts"
}
```
the only "caveat" is that imports are now from `.primsa/client` instead of `@prisma/client` let me know if this works for you!

**Comment by yovanoc** [comment]
Yes that's what I've done to fix this too, but there is a real problem in the package.json of @pothos/plugin-prisma

**Comment by hayes** [comment]
This should be pretty straight forward to add, feel free to open a PR!

**Comment by GauBen** [comment]
Hey!

I've tried modifying the package.json to add node16-style exports:

```jsonc
{
  // ...
  "exports": {
    "./generated": {
      "types": "./generated.ts"
    },
    ".": {
      "import": {
        "default": "./esm/index.js"
      },
      "require": {
        "types": "./dts/index.d.ts",
        "default": "./lib/index.js"
      }
    }
  }
}
```

This almost works, because it now requires a `.default` suffix to be properly used

```ts
import type PrismaTypes from '@pothos/plugin-prisma/generated';

export const builder = new SchemaBuilder<{
  PrismaTypes: PrismaTypes.default;
}>();
```

It might be more elegant as `import type { PrismaTypes }` to avoid the `.default` hack.

What do you think?

**Comment by hayes** [comment]
I wonder if this might work better if the generated file was output to both ./generated.ts and ./esm/generated.ts, the you could have both an import and a require entry in exports for generated.   This should avoid the issue with needing the extra .default, because everything inside the esm directory should be treated as esm instead of cjs (I think this is what's causing the wrappping in `default`, since the genrated file is technically in a cjs package)

**Comment by hayes** [comment]
just pushed a new version that generates both an esm and cjs version when you don't add a custom output location, and adds exports for both version in package.json.

Let me know if you still have issues after updating!

**Comment by GauBen** [comment]
Thanks for the fix!

**Comment by hayes** [comment]
@revero-doug just published a new version with that fix

**Comment by hayes** [comment]
@batur this was about a specific issue related to new typescript settings changing how module resolution works.  

Can you confirm a few things to see if this a new issue:

* The generated file actually exists with generated code (if not make sure you added the Pothos generator and run Prisma generate)
* you are on the latest version of Pothos (core and Prisma plugin)

if you checked both of the above and the generated file exists in the expected location, but typescript still can't find the definitions, could you share your node version, typescript version, if you are using esm or commonjs, and any other build tools that may be relevant to reproduce the issue?
