### ISSUE TITLE
function parameter suggestion

### ISSUE THREAD

**Issue by hyusetiawan** [hayes/pothos#668]
might be a far-fetched request, because how backward incompatible it is, but here it goes!

I see inconsistencies in the function callbacks, for example, which parameter is context which means in terms of DX, I would create the function like so:
`resolve(_, __, ___)` and mouse over one by one to see which one is Context, then rename it from __ to ctx. 

I wonder if it will be better if it's an object instead, like so: `resolve({context, args})` at least this way, we do not have to guess the order.

**Comment by hayes** [comment]
resolver arguments match the underlying graphql.js implementation.

The goal is that there is 0 overhead added by pothos, because resolvers are passed directly to graphql.js without modification.  Obviously some plugins do need to wrap resolvers to implement their behavior, but this is only applied when absolutely necessary.   Wrapping every resolver with a function that wraps arguments in an extra object creates a lot of extra objects that need to be garbage collected, and an extra layer of function wrapping that could be avoided, so this is probably not a change I will make.
