### ISSUE TITLE
The type of ID arguments is not accurate in resolvers

### ISSUE THREAD

**Issue by Emilios1995** [hayes/pothos#694]
When defining a field with an argument whose type is `ID` (created with `t.arg.id()`), the arg in the resolver is typed as `number | string`.

I don't think type is correct, since, while the spec doesn't specify how IDs should be parsed, the `graphql-js` implementation [converts](https://github.com/graphql/graphql-js/blob/main/src/type/scalars.ts#L238) numbers to strings. So the type in the resolver should just be `string`. 

Please let me know whether I'm missing anything and whether I can help.

**Comment by KROSF** [comment]
you can fix that adding scalar typings

```ts
export const builder = new SchemaBuilder<{
  Scalars: {
    ID: {
      Output: string;
      Input: string;
    };
  };
}>({});
```

**Comment by hayes** [comment]
The above is the correct answer for now.

This will be updated in the next major version.  While newer versions of most libraries now convert IDs to strings, this wasn't always the case, and because type-safety was a very big concern, the default was to assume IDs could be numbers, but allow it to be overwritten as described above.

I would still recommend `Output: string | number;` as this is safe, and often more convenient when you have numeric IDs in your internal data representations.
