### ISSUE TITLE
GraphQL Shield Plugin - Error - "Received multiple implementations"

### ISSUE THREAD

**Issue by kungfoolabs** [hayes/pothos#696]
Hi everyone,

I am using GraphQL Shield with NextJS, Prisma,  & Pothos. I've literally copied the exact code from the graphql-shield example: 
https://github.com/hayes/pothos/blob/main/examples/graphql-shield/src/shield-plugin.ts

While, I am running everything in devmode, but there is no hotreloading. However, when I make two pages refreshes, the subsequent request to my graphQL API, I end up getting the following error:

`Error: Received multiple implementations for plugin shield`

My pothos configuration looks like this:

```
import SchemaBuilder from "@pothos/core";
import { DateResolver } from "graphql-scalars";

import PrismaPlugin from "@pothos/plugin-prisma";
import type PrismaTypes from "@pothos/plugin-prisma/generated";

import ShieldPlugin from "lib/pothos-graphql-shield-plugin";
import { prisma } from "./prisma";

if(process.env.NODE_ENV !== 'production') {
  // SchemaBuilder.allowPluginReRegistration = true;
}

export const builder = new SchemaBuilder<{
  Scalars: {
    Date: { Input: Date; Output: Date };
  };
  PrismaTypes: PrismaTypes;
}>({
  plugins: [PrismaPlugin, ShieldPlugin],
  prisma: {
    client: prisma
  }
});
```

Now, this would make sense for me if some my import of the plugin was being reevaluated twice, but I am not sure why that would be the case. Separately, I am also using the `PrismaPlugin` and that works fine if I remove the import and addition of the `ShieldPlugin`. 

It works if I add `allowPluginReRegistration` but I don't think this is the right thing to do since it's not a result of hotreloading.

Any ideas or help would be greatly appreciated?

**Comment by hayes** [comment]
This is a side effect of how next.js works, and allowPluginReRegistration was added for someone with this exact situation (custom plugin inside a next app).

Basically, the way that next works (as far as I know) is that it removes all user code from the module cache on every request, but preserves node_modules between requests.  This is effectively hot-reloading all user code on every request.  This means that your plugin file will get re-evaluated on each request.  This doesn't happen with the prisma plugin, because it is loaded from node_modules, so next.js doesn't remove it from the module cache.

**Comment by kungfoolabs** [comment]
Ah! I see. Thanks @hayes - that makes a lot of sense. Closing the issue.
