### ISSUE TITLE
Duplicate typename error while setting up Pothos in a relay-compatible GraphQL server

### ISSUE THREAD

**Issue by julioxavierr** [hayes/pothos#853]
Hey everyone,

I'm currently setting up Pothos in an existing relay-compatible GraphQL server built with graphql-js. I was able to reuse my existing types using "AddGraphQLPlugin", but after adding the "RelayPlugin" and trying to create a connection, I encountered the following error:

```bash
PothosSchemaError: Duplicate typename: Another type with name PageInfo already exists.
```

I'm not sure how to proceed from here, and I was hoping someone could help me out. I'm wondering if there's a way to reference that the type already exists or rename the PageInfo type for now. I'd appreciate any advice or guidance on how to resolve this issue.

Thanks in advance!

**Comment by hayes** [comment]
I suspect the issue is that the pageInfo object is being created very late by the relay plugin, so when the add-graphql plugin checks if your schema has a pageInfo object, it doesn't exist yet and it adds the one from the old schema.

try calling builder.pageInfo() after setting up the builder (maybe builder.nodeRef() too).  This will create references to those types earlier and hopefully avoid the conflict

**Comment by julioxavierr** [comment]
@hayes I sincerely appreciate your prompt response! Your solution resolved the issue and spared me from having to resort to potentially problematic package patching.
