### ISSUE TITLE
Type issue: required/optional fields

### ISSUE THREAD

**Issue by pciporin25** [hayes/pothos#885]
Hello, I am in the process of upgrading `@pothos/core` from version `3.10.1` to the latest `3.29.0` and am encountering a strange type issue with existing (and functional) code.  Consider the following [sample code](https://github.com/theogravity/graphql-pothos-server-example/pull/3):

```
const SampleInput = builder.inputType('SampleInput', {
  fields: (t) => ({
    requiredField: t.string({
      required: true,
    }),
    optionalField: t.string({
      required: false,
    }),
  }),
});

builder.mutationField('sampleMutation', (t) => {
  return t.field({
    type: 'Boolean',
    args: {
      input: t.arg({
        required: true,
        type: SampleInput,
      }),
    },
    resolve: async (_, args) => {
     // TypeScript error occurs here
      return sampleResolver(args.input);
    },
  });
});

const sampleResolver = ({
  requiredField,
  optionalField,
}: {
  requiredField: string;
  optionalField?: string;
}) => {
  console.log({ requiredField, optionalField });
  return true;
};
```

On version `3.10.1` I see no type errors, but after upgrading to the latest I get the following TypeScript error when invoking the `sampleResolver`:
>   Property 'requiredField' is optional in type 'InputShapeFromFields<{ requiredField: InputFieldRef<string, "InputObject">; optionalField: InputFieldRef<string, "InputObject">; }>' but required in type '{ requiredField: string; optionalField?: string; }'.

I can see that on both the old and new version, the `input` object is of the following type:

```
(property) input?: InputShapeFromFields<{
    requiredField: InputFieldRef<string, "InputObject">;
    optionalField: InputFieldRef<string, "InputObject">;
}>
```

Note that it appears that the `required` is not being taken into account, but I'm unsure why the error would only be appearing on the latest version of `@pothos/core`.  I tried enabling `"strict": true` in `tsconfig.json` (and later only `"strictNullChecks": true, "strictPropertyInitialization": true,`) which seems to correct the input type:

```
(property) input: InputShapeFromFields<{
    requiredField: InputFieldRef<string, "InputObject">;
    optionalField: InputFieldRef<string | null | undefined, "InputObject">;
}>
```

However, I am then left with the following TypeScript error:
>   Types of property 'optionalField' are incompatible.
    Type 'string | null | undefined' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.

Do you know what might have changed between `@pothos/core` versions `3.10.1` and `3.29.0` that might have caused these TypeScript errors to appear, and do you have any suggestions for resolving them?  Thank you in advance!

**Comment by hayes** [comment]
I don't know exactly what changed, but the behavior from the newer version in strict mode looks correct.

The proper typing for the resolver would be something like:
```ts
const sampleResolver = ({
  requiredField,
  optionalField,
}: {
  requiredField: string;
  optionalField?: string | null;
}) => {
  console.log({ requiredField, optionalField });
  return true;
};
```

Optional arguments in Pothos are typed ads `T | null | undefined` because GraphQL supports explicitly sending nulls or omitting the arguments entirely (which would be received as `undefined`)  This is behavior that comes from graphql-js and the various graphql server implementations.  Pothos is just trying to be strict about what the potential types are.

There was likely some sort of change in the `InputShapeFromFields` helper that does not produce the expected types when strict mode is disabled, although I don't know exactly what it is.  strict mode (mostly `strictNullChecks` is required for pothos to work correctly.  

I have generally tried to keep things as functional as possible with strict mode disabled, but this is not something that well tested.

**Comment by pciporin25** [comment]
Thanks @hayes for the quick response.  It sounds like enabling strict mode and modifying the resolver as you suggested is the solution here.  Appreciate the explanation!
