### ISSUE TITLE
Pothos prisma ignores nullable relations and causes graphql to throw unexpected exceptions

### ISSUE THREAD

**Issue by garth** [hayes/pothos#945]
When a table has a non-nullable foreign key to another table. When joining the two tables it is still possible for the relation to return null when the Row Level Security policy in postgres forbids access to the related record. The typescript generated by the pothos prisma plugin does correctly reflect this but the graphql schema generated does not, which will cause an unexpected exception to be thrown by graphql.

```prisma
model PersonDocument {
  documentId Int           
  personId   Int           
  document   Document? @relation(fields: [documentId], references: [id])
  person     Person    @relation(fields: [personId], references: [id])

  @@id([documentId, personId])
}
```

in the database add a RLS policy to block access to the document.

```sql
CREATE POLICY document_read ON document FOR SELECT TO my_db_user USING (false);
```

In the prisma schema above, notice that the `documentId` is non-nullable but the Document relation is marked with a `?`. This is enough to let prisma know that nullable relations are expected. the generated prisma client correctly shows `document` as nullable and so does the generated pothos types:

```ts
          Relations: {
            document: {
                Shape: Document | null; // looks correct
                Name: "Document";
            };
            person: {
                Shape: Person;
                Name: "Person";
            };
        };
```

But when pothos then generates the graphql schema the document relation is marked as non-nullable.

```graphql
type PersonDocument {
  person: Person!
  person: ID!
  document: Document!    # this should be nullable
  documentId: ID!
}
```

When the current db user does not have access to the related document record you get the following error from graphql:

```
Error: Cannot return null for non-nullable field PersonDocument.document.
```

**Comment by garth** [comment]
I think I've tracked down the issue to 

https://github.com/hayes/pothos/blob/92e1cc8cce529a854d5ada46b6035e93dac8be07/packages/plugin-prisma/src/generator.ts#L275

at which point I wonder if this is a bug in prisma?

**Comment by garth** [comment]
Nope, I don't think it's prisma... I've added some unit tests to a local copy of the prisma src and it seem to be outputting the correct field dmmf config.

**Comment by hayes** [comment]
Pothos doesn't determine if a relation is nullable based on the schema, you need to manually add nullable: true when you define the relationship

**Comment by hayes** [comment]
This isn't documented well, and it's not entirely obvious.  Unfortunately there isn't really a good way to handle this, with all the options having downsides.

There are a number of very common patterns:
* optional relations that a user wants to have non-nullable in the GraphQL api
* required relations that the user wants to have nullable in the GraphQL api
* users who want to change nullabilit of GraphQL and DB schema independently
* users who expect the default nullability to match the DB schema
* users who expect the default to match the defaults for fields set up for their builder

In this case I decided using the default nullability from the schema builder made the most sense.  Part of this is motivated by a core rule I try to follow which is that the generated GraphQL schema shouldn't change unless you change how the the definitions in Pothos.  The prisma plugin violates this in a couple places (field descriptions will be updated from the prisma schema, and if you change the type of a relation it would technically change the schema) but generally the API is designed so that if you change your data (the prisma schema in this case) the generated schema shouldn't change, instead you should get typescript or build errors).

Generally what I should have done is make `nullable: true` a required setting if the relation is nullable, but there were several key use cases from early adopters who had nullable relations that wanted them to be non-nullable in the GraphQL schema, so I removed that requirement.

**Comment by garth** [comment]
In my case I had a non-nullable relation a -> b. But later added row level security to the database, so that even though a.b_id was non-nullable, some a.b values returned by prisma would be null. I updated the prisma schema, but completely forgot that nullability is not propagated.

It does seem that the most obvious default would be to mirror what is defined in the prisma schema and allow the developer to override (if necessary), but it's not a huge issues, just have to remember next time.
